# Generated by Django 5.1.1 on 2024-11-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='province',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='social_security_number',
        ),
        migrations.RemoveField(
            model_name='userinformation',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='userinformation',
            name='GCS',
            field=models.CharField(max_length=5, null=True, verbose_name='GCS'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='HR',
            field=models.CharField(max_length=5, null=True, verbose_name='HR'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='O2',
            field=models.CharField(max_length=5, null=True, verbose_name='O2'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='RR',
            field=models.CharField(max_length=5, null=True, verbose_name='RR'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='age',
            field=models.CharField(max_length=5, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='birth_place',
            field=models.CharField(max_length=25, null=True, verbose_name='Birth Place'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='blood_pressure',
            field=models.CharField(max_length=5, null=True, verbose_name='Blood Pressure'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='Blood Type'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='citizenship',
            field=models.CharField(max_length=20, null=True, verbose_name='Citizenship(s)'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='civil_status',
            field=models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=9, null=True, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='company',
            field=models.CharField(max_length=20, null=True, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='company_address',
            field=models.CharField(max_length=20, null=True, verbose_name='Company Address'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='first_name',
            field=models.CharField(max_length=20, null=True, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isAmericanIndian',
            field=models.BooleanField(null=True, verbose_name='American Indian or Alaska Native'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isAsian',
            field=models.BooleanField(null=True, verbose_name='Asian'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isBlack',
            field=models.BooleanField(null=True, verbose_name='Black or African American'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isChild',
            field=models.BooleanField(null=True, verbose_name='Child?'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isConfidentialPatientRecord',
            field=models.BooleanField(null=True, verbose_name='Confidential Patient Record'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isFictitiousBirthDate',
            field=models.BooleanField(null=True, verbose_name='Fictitious Birth Date'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isHispanic',
            field=models.BooleanField(null=True, verbose_name='Hispanic or Latino'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isHospitalEmp',
            field=models.BooleanField(null=True, verbose_name='Hospital Employee?'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isNativeHawaiian',
            field=models.BooleanField(null=True, verbose_name='Native Hawaiian or Other Pacific Islander'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isNoCompanyCommunication',
            field=models.BooleanField(null=True, verbose_name='No communication from company?'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isNoPersonalDataRelease',
            field=models.BooleanField(null=True, verbose_name='No personal data released to other parties?'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isNonLocal',
            field=models.BooleanField(null=True, verbose_name='Non-Local?'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='isWhite',
            field=models.BooleanField(null=True, verbose_name='White'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='last_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='middle_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='mr_locator_no',
            field=models.CharField(max_length=10, null=True, verbose_name='M.R Locator No.'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='nationality',
            field=models.CharField(choices=[], max_length=25, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='occupation',
            field=models.CharField(max_length=20, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='passport_number',
            field=models.CharField(max_length=9, null=True, verbose_name='Passport No.'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='patient_identification',
            field=models.CharField(max_length=10, null=True, verbose_name='Patient ID'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='patient_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Patient Number'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='patient_phic_number',
            field=models.CharField(max_length=10, null=True, verbose_name='Patient Phic No.'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='patient_tin_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Patient Tin No.'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='philID',
            field=models.CharField(max_length=12, null=True, verbose_name='PhilID'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='remarks',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Remarks'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='sss_number',
            field=models.CharField(max_length=9, null=True, verbose_name='SSS No.'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='suffix_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Suffix Name'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='temperature',
            field=models.CharField(max_length=5, null=True, verbose_name='Temperature'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='weight',
            field=models.CharField(max_length=5, null=True, verbose_name='Weight'),
        ),
        migrations.AddField(
            model_name='userinformation',
            name='xray_file_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Xray File No.'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='religion',
            field=models.CharField(choices=[], max_length=25, null=True, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender / Sex'),
        ),
    ]
