# Generated by Django 5.1.1 on 2024-11-04 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('religion', models.CharField(max_length=50, verbose_name='Religion')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex')),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=9, verbose_name='Marital Status')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('social_security_number', models.CharField(max_length=9, verbose_name='Social Security Number')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('province', models.CharField(max_length=50, verbose_name='Province')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('contact_number', models.CharField(max_length=11, verbose_name='Contact Number')),
                ('zip_code', models.CharField(max_length=4, verbose_name='Zip Code')),
                ('mother_name', models.CharField(max_length=50, verbose_name="Mother's Name")),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='random_index', verbose_name='User')),
            ],
        ),
    ]
