# Generated by Django 5.1.1 on 2024-11-13 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_userinformation_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeypasswords',
            name='index',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='random_index', verbose_name='User'),
        ),
        migrations.CreateModel(
            name='UserGeneralInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Last Name')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=20, null=True, verbose_name='Middle Name')),
                ('suffix_name', models.CharField(max_length=20, null=True, verbose_name='Suffix Name')),
                ('civil_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=9, null=True, verbose_name='Marital Status')),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='Gender / Sex')),
                ('nationality', models.CharField(choices=[], max_length=25, null=True, verbose_name='Nationality')),
                ('religion', models.CharField(choices=[], max_length=25, null=True, verbose_name='Religion')),
                ('philID', models.CharField(max_length=12, null=True, verbose_name='PhilID')),
                ('sss_number', models.CharField(max_length=9, null=True, verbose_name='SSS No.')),
                ('passport_number', models.CharField(max_length=9, null=True, verbose_name='Passport No.')),
                ('birth_date', models.DateField(null=True, verbose_name='Birth Date')),
                ('age', models.CharField(max_length=5, null=True, verbose_name='Age')),
                ('birth_place', models.CharField(max_length=25, null=True, verbose_name='Birth Place')),
                ('citizenship', models.CharField(max_length=20, null=True, verbose_name='Citizenship(s)')),
                ('company', models.CharField(max_length=20, null=True, verbose_name='Company')),
                ('company_address', models.CharField(max_length=20, null=True, verbose_name='Company Address')),
                ('remarks', models.CharField(blank=True, max_length=40, null=True, verbose_name='Remarks')),
                ('occupation', models.CharField(max_length=20, null=True, verbose_name='Occupation')),
                ('isAmericanIndian', models.BooleanField(null=True, verbose_name='American Indian or Alaska Native')),
                ('isAsian', models.BooleanField(null=True, verbose_name='Asian')),
                ('isBlack', models.BooleanField(null=True, verbose_name='Black or African American')),
                ('isHispanic', models.BooleanField(null=True, verbose_name='Hispanic or Latino')),
                ('isWhite', models.BooleanField(null=True, verbose_name='White')),
                ('isNativeHawaiian', models.BooleanField(null=True, verbose_name='Native Hawaiian or Other Pacific Islander')),
                ('isChild', models.BooleanField(null=True, verbose_name='Child?')),
                ('isNonLocal', models.BooleanField(null=True, verbose_name='Non-Local?')),
                ('isHospitalEmp', models.BooleanField(null=True, verbose_name='Hospital Employee?')),
                ('isNoPersonalDataRelease', models.BooleanField(null=True, verbose_name='No personal data released to other parties?')),
                ('isNoCompanyCommunication', models.BooleanField(null=True, verbose_name='No communication from company?')),
                ('isFictitiousBirthDate', models.BooleanField(null=True, verbose_name='Fictitious Birth Date')),
                ('isConfidentialPatientRecord', models.BooleanField(null=True, verbose_name='Confidential Patient Record')),
                ('index', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='random_index', verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Information',
                'verbose_name_plural': 'User Information',
            },
        ),
        migrations.CreateModel(
            name='UserMedicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.CharField(max_length=10, null=True, verbose_name='Patient Number')),
                ('patient_identification', models.CharField(max_length=10, null=True, verbose_name='Patient ID')),
                ('patient_tin_number', models.CharField(max_length=20, null=True, verbose_name='Patient Tin No.')),
                ('patient_phic_number', models.CharField(max_length=10, null=True, verbose_name='Patient Phic No.')),
                ('mr_locator_no', models.CharField(max_length=10, null=True, verbose_name='M.R Locator No.')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True, verbose_name='Blood Type')),
                ('weight', models.CharField(max_length=5, null=True, verbose_name='Weight')),
                ('temperature', models.CharField(max_length=5, null=True, verbose_name='Temperature')),
                ('blood_pressure', models.CharField(max_length=5, null=True, verbose_name='Blood Pressure')),
                ('GCS', models.CharField(max_length=5, null=True, verbose_name='GCS')),
                ('O2', models.CharField(max_length=5, null=True, verbose_name='O2')),
                ('HR', models.CharField(max_length=5, null=True, verbose_name='HR')),
                ('RR', models.CharField(max_length=5, null=True, verbose_name='RR')),
                ('xray_file_number', models.CharField(max_length=20, null=True, verbose_name='Xray File No.')),
                ('index', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='random_index', verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Medical Information',
                'verbose_name_plural': 'User Medical Information',
            },
        ),
        migrations.DeleteModel(
            name='UserInformation',
        ),
    ]
