# Generated by Django 5.1.1 on 2024-11-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_honeypasswords_index_usergeneralinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergeneralinformation',
            name='suffix_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Suffix Name'),
        ),
    ]
