# Generated by Django 5.1.1 on 2024-11-10 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'CustomUser', 'verbose_name_plural': 'CustomUsers'},
        ),
        migrations.AlterModelOptions(
            name='userinformation',
            options={'verbose_name': 'User Information', 'verbose_name_plural': 'User Information'},
        ),
        migrations.DeleteModel(
            name='HoneyPasswords',
        ),
    ]
