# Generated by Django 5.1.1 on 2024-11-10 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='random_index',
            field=models.IntegerField(blank=True, max_length=4, null=True, unique=True, verbose_name='Random Index'),
        ),
        migrations.CreateModel(
            name='HoneyPasswords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honeyPasswords', models.JSONField(default=list)),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='random_index', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Honey Password',
                'verbose_name_plural': 'Honey Passwords',
            },
        ),
    ]
