# Generated by Django 5.1.1 on 2024-11-21 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_usergeneralinformation_isfictitiousbirthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='honeypasswords',
            name='id',
        ),
        migrations.AlterField(
            model_name='honeypasswords',
            name='index',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, to_field='random_index', verbose_name='User'),
        ),
    ]
