# Generated by Django 5.1.1 on 2024-11-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_customuser_random_index_honeypasswords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='random_index',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Random Index'),
        ),
    ]
