# Generated by Django 5.1.1 on 2025-03-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_honeypasswords_id_alter_honeypasswords_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='honeypasswords',
            name='salt',
            field=models.CharField(max_length=20, null=True, verbose_name='Salt'),
        ),
    ]
