# Generated by Django 5.1.1 on 2025-03-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_honeypasswords_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='honeypasswords',
            name='salt',
            field=models.CharField(max_length=100, null=True, verbose_name='Salt'),
        ),
    ]
