# Generated by Django 5.1.1 on 2025-03-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_honeypasswords_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='age',
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='isAmericanIndian',
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='isAsian',
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='isBlack',
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='isChild',
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='isHispanic',
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='isHospitalEmp',
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='isNativeHawaiian',
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='isNonLocal',
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='isWhite',
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='remarks',
        ),
        migrations.AddField(
            model_name='usergeneralinformation',
            name='race',
            field=models.CharField(choices=[('American', 'American')], max_length=20, null=True, verbose_name='Race'),
        ),
    ]
