# Generated by Django 5.1.1 on 2025-03-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_remove_usergeneralinformation_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergeneralinformation',
            name='isNonLocal',
            field=models.BooleanField(null=True, verbose_name='Non-Local?'),
        ),
        migrations.AlterField(
            model_name='usergeneralinformation',
            name='race',
            field=models.CharField(choices=[('American', 'American'), ('Asian', 'Asian'), ('Black', 'Black or African American'), ('White', 'White'), ('Hispanic', 'Hispanic or Latino'), ('NativeAmerican', 'Native American'), ('PacificIslander', 'Native Hawaiian or Pacific Islander'), ('Multiracial', 'Two or More Races'), ('Other', 'Other')], max_length=20, null=True, verbose_name='Race'),
        ),
    ]
