# Generated by Django 5.1.1 on 2025-03-25 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_usergeneralinformation_isnonlocal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='company_address',
        ),
    ]
