# Generated by Django 5.1.1 on 2025-03-25 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_remove_usergeneralinformation_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergeneralinformation',
            name='citizenship',
        ),
    ]
