# Generated by Django 5.1.1 on 2025-03-25 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_remove_usergeneralinformation_citizenship'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedSeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciphertext', models.TextField()),
                ('rbmrsa_parameters', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('index', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='random_index', verbose_name='User')),
            ],
        ),
    ]
